### ISSUE TITLE
@registry can have duplicate output filenames (defaults)

### ISSUE THREAD

**Issue by pb-cdunn** [PacificBiosciences/pbsmrtpipe#258]
With `@registry`, if you produce two output files of the same FileType, they use the same default name, so they collide. In the task def, the filenames are the same. (Oddly, there are no errors.)

Is there a way to over-ride the default file names via `@registry`? (I see an example, `dev_txt_hello`, but that pipeline does not have a TC.)

**Comment by mpkocher** [comment]
I believe you're referencing the quick TC registry model in pbcommand? If so, can we move this pbcommand?

**Comment by mpkocher** [comment]
This bug existed in an earlier version and I believe it was fixed. Now there is a unique id ("label") assigned. There should be a unittest for this specific case.

For custom output file names, see the "dev_txt_custom_outs" example for how to have custom default names within the registry model.

The fourth argument to `@registry` is a single value or a list/tuple of either an explicit instance of OutputFileType, or a FileTypes.X.

**Comment by pb-cdunn** [comment]
> This bug existed in an earlier version and I believe it was fixed. Now there is a unique id ("label") assigned. There should be a unittest for this specific case.

Yes, the label is unique, but the filename is not.

I am using
```
commit a405fc93a92d6738a4e3a24a04dd98c12a5bd392
Merge: 3479e84 a95559c
Author: Michael <michael.kocher@me.com>
Date:   Tue Dec 22 17:22:21 2015

    Merge pull request #46 from PacificBiosciences/report-name

    Add title to Report model. Update to 0.3.9
```
As of that commit, the bug still exists.

> The fourth argument to @registry is a single value or a list/tuple of either an explicit instance of OutputFileType, or a FileTypes.X.

I've been using `OutputFileType(..., default_name)` as a work-around. That's verbose, but it works. (**pbcommand** seems to over-ride the file extension, but that's fine with me.) If that's the recommended way to do this, you can close this.

**Comment by pb-cdunn** [comment]
I just double-checked (in case I'd forgotten to update TCs in my earlier testing). When I generate TCs from my @registry-decorated functions, I get the same `default_name` in the TCs when a task has 2 outputs of the same FileType. And at runtime, the task gets the same filename twice.
Again, not a big deal to me. I'm just mentioning.

**Comment by mpkocher** [comment]
Can you provide the explicit "default_name" value that you were using?

My guess is that is related to the ambiguity of supplying the "default_name" format as "basename.ext" or "basename", which might not be handled gracefully in TC resolving process to determine the output file name(s).

The newer basename only model is the preferred approach. The file extension is unnecessary and will be determined from the file_type_id that is passed in. This prevents supplying a Fasta File type and writing "file.bam". It also avoid guessing the file extension from the file to create unique file names (the output format is {my-base-name}-{Int}.{ext} )

**Comment by pb-cdunn** [comment]
It works fine when I use my own instances of OutputFileType; that's how I can provide my own default_names. But when I just use `FileTypes.TXT`, all the outputs have `file.txt` as the default.
